Monkey test occur NullPointerException in SYSTEM PROCESS.
Process: system_server

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.android.server.job.controllers.JobStatus.getName()' on a null object reference
	at com.android.server.job.JobServiceContext$JobServiceHandler.closeAndCleanupJobH(JobServiceContext.java:530)
	at com.android.server.job.JobServiceContext$JobServiceHandler.handleMessage(JobServiceContext.java:335)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at com.android.server.SystemServer.run(SystemServer.java:293)
	at com.android.server.SystemServer.main(SystemServer.java:177)

[root cause  ] mRunningJob is null when call getName.
[Solution    ] check whether the mRunningJob[completedJob] is null when call mBatteryStats.noteJobFinish to avoid the NPE.

Test: monkey test 24h with no crash of system_server process.

Change-Id: Ib7f0fd21a26b9a1a48c5abafff832c7eba1eaae0